import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { FileEdit, Sparkles, Download, Wand2, Plus, RefreshCw, Minimize2, FileText } from "lucide-react";
import { proposalSections } from "@/lib/mock-data";

export const Route = createFileRoute("/proposal")({
  head: () => ({ meta: [{ title: "Proposal Builder — BidPilot AI" }] }),
  component: ProposalPage,
});

const bodyMock: Record<string, string> = {
  exec: "Our team is uniquely positioned to deliver the National Citizen Services Platform on time and within budget. Drawing on 12 years of federal-grade engagements — including the Federal Tax Authority ERP rollout (2024) and the Citizen Identity Wallet pilot (2025) — we bring proven methodology, ISO 27001-certified delivery, and a regional team already cleared for in-country hosting.",
  und: "We understand the Ministry of Digital Affairs requires a citizen-first, accessible, cloud-native platform with multi-region resilience, eID integration, and Arabic + English UI. Section 4.2 emphasizes a 99.95% SLA and WCAG 2.2 AA accessibility. Our reading of the RFP identifies 20 explicit requirements grouped into Mandatory, Technical, Financial, Legal, and Submission categories…",
};

function ProposalPage() {
  const [active, setActive] = useState("exec");

  return (
    <div className="space-y-5">
      <header className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 sm:flex sm:flex-wrap sm:justify-between">
        <div className="flex min-w-0 items-center gap-3">
          <div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-neon-violet/15 neon-border-blue">
            <FileEdit className="h-5 w-5 text-neon-violet" />
          </div>
          <div className="min-w-0">
            <span className="font-mono text-[10px] uppercase tracking-[0.22em] text-neon-cyan">Module · MOD-05</span>
            <h1 className="font-display text-2xl font-bold sm:text-3xl">Proposal Builder</h1>
          </div>
        </div>
        <button className="inline-flex items-center gap-2 rounded-lg bg-gradient-to-r from-neon-blue to-neon-violet px-4 py-2.5 text-sm font-semibold text-background">
          <Download className="h-4 w-4" /> Export DOCX
        </button>
      </header>

      <div className="grid grid-cols-1 gap-5 xl:grid-cols-[260px_minmax(0,1fr)_320px]">
        {/* Left: Section navigator */}
        <aside className="glass-strong rounded-2xl p-3">
          <div className="px-2 py-1 font-mono text-[10px] uppercase tracking-[0.22em] text-neon-cyan">Sections</div>
          <ul className="mt-2 space-y-1">
            {proposalSections.map((s, i) => (
              <li key={s.id}>
                <button
                  onClick={() => setActive(s.id)}
                  className={`flex w-full items-center gap-3 rounded-lg px-3 py-2 text-left transition ${active === s.id ? "bg-neon-blue/15 text-neon-cyan neon-border-blue" : "text-muted-foreground hover:bg-white/5 hover:text-foreground"}`}
                >
                  <span className={`grid h-7 w-7 place-items-center rounded-md font-mono text-[10px] ${active === s.id ? "bg-neon-cyan/20 text-neon-cyan" : "bg-surface-1 text-muted-foreground"}`}>
                    {(i + 1).toString().padStart(2, "0")}
                  </span>
                  <div className="min-w-0 flex-1">
                    <div className="truncate text-[13px] font-medium">{s.title}</div>
                    <div className="font-mono text-[9px] text-muted-foreground">{s.words} words</div>
                  </div>
                </button>
              </li>
            ))}
          </ul>
          <button className="mt-3 flex w-full items-center justify-center gap-1.5 rounded-lg border border-dashed border-white/10 py-2 text-[11px] text-muted-foreground hover:text-foreground">
            <Plus className="h-3 w-3" /> Add Section
          </button>
        </aside>

        {/* Center: Editor */}
        <section className="glass-strong overflow-hidden rounded-2xl">
          <div className="flex items-center justify-between border-b border-white/5 px-5 py-3">
            <div className="flex items-center gap-2">
              <FileText className="h-4 w-4 text-neon-cyan" />
              <span className="font-display text-sm font-semibold">{proposalSections.find(s => s.id === active)?.title}</span>
            </div>
            <span className="font-mono text-[10px] text-muted-foreground">Auto-saved · 2s ago</span>
          </div>
          <div className="p-6">
            <h1 className="font-display text-2xl font-bold">{proposalSections.find(s => s.id === active)?.title}</h1>
            <p className="mt-4 text-[14px] leading-relaxed text-foreground/90">
              {bodyMock[active] ?? "Draft generated by AI. Edit freely — the Co-Pilot will track changes and re-grade compliance in real time."}
            </p>
            <p className="mt-4 text-[14px] leading-relaxed text-foreground/80">
              {/* TODO: connect rich-text editor and backend autosave */}
              Our delivery approach blends SAFe 6.0 Agile with structured risk reviews aligned to Ministry governance gates. Each sprint produces a vertical slice with measurable outcomes, ensuring the Ministry sees tangible progress every two weeks. Quality is reinforced by dual-track engineering, weekly accessibility audits, and a security control matrix mapped to ISO 27001 Annex A.
            </p>
            <div className="mt-6 rounded-xl border border-dashed border-neon-cyan/30 bg-neon-cyan/5 p-4 text-[12.5px] text-neon-cyan/90">
              <span className="font-mono text-[10px] uppercase tracking-wider">AI insight</span>
              <p className="mt-1 text-foreground/90">This section currently matches 4 of 6 mandatory requirements. Add a paragraph on data residency to lift compliance to 100%.</p>
            </div>
          </div>
        </section>

        {/* Right: AI suggestions */}
        <aside className="glass-strong rounded-2xl p-5">
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-neon-violet" />
            <h2 className="font-display text-sm font-semibold">AI Suggestions</h2>
          </div>

          <div className="mt-4 space-y-2">
            {[
              { label: "Improve wording", icon: Wand2 },
              { label: "Add company evidence", icon: Plus },
              { label: "Make it formal", icon: FileText },
              { label: "Shorten section", icon: Minimize2 },
              { label: "Regenerate section", icon: RefreshCw },
            ].map(a => (
              <button key={a.label} className="flex w-full items-center gap-2 rounded-lg bg-surface-1/60 px-3 py-2 text-[12.5px] font-medium hover:bg-neon-blue/10 hover:text-neon-cyan">
                <a.icon className="h-3.5 w-3.5" /> {a.label}
              </button>
            ))}
          </div>

          <div className="mt-5 rounded-xl bg-neon-violet/10 p-3">
            <div className="font-mono text-[10px] uppercase tracking-wider text-neon-violet">Suggested rewrite</div>
            <p className="mt-1.5 text-[12px] leading-relaxed text-foreground/85">
              "Our consortium delivers a citizen-grade platform anchored on three pillars: trust, accessibility, and continuous evolution…"
            </p>
            <div className="mt-2 flex gap-2">
              <button className="rounded-md bg-neon-violet/20 px-3 py-1 text-[11px] text-neon-violet">Apply</button>
              <button className="rounded-md bg-surface-1 px-3 py-1 text-[11px] text-muted-foreground">Dismiss</button>
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}
